name: Pipeline de CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  construir:
    runs-on: ubuntu-latest

    steps:
      - name: Fazer checkout do repositório da API
        uses: actions/checkout@v2
        with:
          repository: 'ErickJulio/apiDados'
          path: './api'

      - name: Fazer checkout do repositório do Cypress
        uses: actions/checkout@v2
        with:
          repository: 'ErickJulio/testeConverterArquivoDocx'
          path: './cypress'

      - name: Configurar o Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Instalar dependências da API
        run: |
          cd ./api
          npm install

      - name: Instalar dependências do Cypress
        run: |
          cd ./cypress
          npm install

      - name: Iniciar API no Render
        run: |
          cd ./api
          npm start &
        env:
          NODE_ENV: test

      - name: Aguardar a API estar pronta
        run: |
          npx wait-on --timeout 400000 --interval 7000 https://api-teste-dados.onrender.com/api-docs
        env:
          NODE_ENV: test

      - name: Executar testes do Cypress
        run: |
          cd ./cypress
          npx cypress run
