name: Node.js CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install
      working-directory: ./api

    - name: Run API
      run: npm start
      working-directory: ./api &
      
    - name: Wait for API to start
      run: sleep 240 # Aguarda 4 minutos para a API subir completamente

    - name: Install Cypress
      run: npm install
      working-directory: ./cypress

    - name: Run Cypress tests
      run: npm run cypress:run
      working-directory: ./cypress
