name: Pipeline de CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  checkout_instalar_dependencias_api:
    name: Checkout e Instalar dependências API
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repositório da API
        uses: actions/checkout@v2
        with:
          repository: 'ErickJulio/apiDados'
      
      - name: Configurar o Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Instalar dependências API
        run: |
          npm install

  checkout_instalar_dependencias_cypress:
    name: Checkout e Instalar dependências Cypress
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repositório do Cypress
        uses: actions/checkout@v2
        with:
          repository: 'ErickJulio/testeConverterArquivoDocx'
      
      - name: Configurar o Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Instalar dependências Cypress
        run: |
          npm install

  iniciar_api:
    name: Iniciar API no Render
    runs-on: ubuntu-latest
    needs: checkout_instalar_dependencias_api
    steps:
      - name: Start API
        run: |
          npm start &
        env:
          NODE_ENV: test

  aguardar_api:
    name: Aguardar a API estar pronta
    runs-on: ubuntu-latest
    needs: iniciar_api
    steps:
      - name: Wait for API
        run: |
          npx wait-on --timeout 400000 --interval 7000 https://api-teste-dados.onrender.com/api-docs
        env:
          NODE_ENV: test

  executar_testes_cypress:
    name: Executar testes do Cypress
    runs-on: ubuntu-latest
    needs: [checkout_instalar_dependencias_cypress, aguardar_api]
    steps:
      - name: Run Cypress Tests
        run: |
          npx cypress run
