name: Pipeline de CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  checkout_api:
    name: Checkout repositório da API
    runs-on: ubuntu-latest
    steps:
      - name: Checkout API
        uses: actions/checkout@v2
        with:
          repository: 'ErickJulio/apiDados'
          path: './api'

  checkout_cypress:
    name: Checkout repositório do Cypress
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Cypress
        uses: actions/checkout@v2
        with:
          repository: 'ErickJulio/testeConverterArquivoDocx'
          path: './cypress'

  configurar_nodejs:
    name: Configurar o Node.js
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

  instalar_dependencias_api:
    name: Instalar dependências API
    runs-on: ubuntu-latest
    needs: checkout_api
    steps:
      - name: Instalar dependências
        run: |
          cd ./api
          npm install

  instalar_dependencias_cypress:
    name: Instalar dependências Cypress
    runs-on: ubuntu-latest
    needs: checkout_cypress
    steps:
      - name: Instalar dependências
        run: |
          cd ./cypress
          npm install

  iniciar_api:
    name: Iniciar API no Render
    runs-on: ubuntu-latest
    needs: instalar_dependencias_api
    steps:
      - name: Start API
        run: |
          cd ./api
          npm start &
        env:
          NODE_ENV: test

  aguardar_api:
    name: Aguardar a API estar pronta
    runs-on: ubuntu-latest
    needs: iniciar_api
    steps:
      - name: Wait for API
        run: |
          npx wait-on --timeout 400000 --interval 7000 https://api-teste-dados.onrender.com/api-docs
        env:
          NODE_ENV: test

  executar_testes_cypress:
    name: Executar testes do Cypress
    runs-on: ubuntu-latest
    needs: [instalar_dependencias_cypress, aguardar_api]
    steps:
      - name: Run Cypress Tests
        run: |
          cd ./cypress
          npx cypress run
